name = "arbitrage-digest-bot1"
main = "index.js"
compatibility_date = "2026-01-01"

[vars]
CHAT_ID = "783355102"

kv_namespaces = [
  { binding = "DIGEST", id = "89d32d48bb784fa9b89702f84129c2f7" }
]

# Каждые 15 минут воркер проверяет, не появился ли новый digest.json
[triggers]
crons = ["*/15 * * * *"]
